import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import './globals.css'
import { ImageProvider } from '@/components/image-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="h-screen bg-background font-sans antialiased">
        <Toaster position="top-center" richColors />
        <ImageProvider>{children}</ImageProvider>
      </body>
    </html>
  )
}
